# Generated by Django 4.2.7 on 2025-11-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='DevolucionProveedor',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('productos_devueltos', models.TextField(blank=True, null=True)),
                ('cantidad_devuelta', models.IntegerField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Devolucion_Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('rol', models.CharField(blank=True, max_length=100, null=True)),
                ('funciones', models.TextField(blank=True, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id_factura_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Factura_Compra',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_factura_compra', models.ForeignKey(blank=True, db_column='id_factura_compra', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.facturacompra')),
            ],
            options={
                'db_table': 'Lote',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_generico', models.CharField(max_length=255)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('contra_indicaciones', models.TextField(blank=True, null=True)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_laboratorio', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_sanitario', models.CharField(blank=True, max_length=100, null=True)),
                ('precauciones', models.TextField(blank=True, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_minimo', models.IntegerField(default=10)),
                ('via_administracion', models.CharField(blank=True, max_length=100, null=True)),
                ('requiere_receta', models.BooleanField(default=False)),
                ('estado', models.IntegerField(default=1)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_factura_compra', models.ForeignKey(blank=True, db_column='id_factura_compra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia_app.facturacompra')),
            ],
            options={
                'db_table': 'Medicamento',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('tipo_proveedor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia_app.cliente')),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia_app.empleados')),
            ],
            options={
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='PresentacionMedicamento',
            fields=[
                ('id_presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('id_medicamento', models.ForeignKey(blank=True, db_column='id_medicamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.medicamento')),
            ],
            options={
                'db_table': 'Presentacion_Medicamento',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.venta')),
            ],
            options={
                'db_table': 'Metodo_Pago',
            },
        ),
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id_lote_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('id_lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.lote')),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.medicamento')),
            ],
            options={
                'db_table': 'Lote_Medicamento',
            },
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.proveedor'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_medicamento', models.ForeignKey(blank=True, db_column='id_medicamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.medicamento')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.venta')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='EstadoDevolucionProveedor',
            fields=[
                ('id_estado_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_devolucion', models.ForeignKey(blank=True, db_column='id_devolucion', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.devolucionproveedor')),
            ],
            options={
                'db_table': 'Estado_Devolucion_Proveedor',
            },
        ),
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id_estado_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.facturacompra')),
            ],
            options={
                'db_table': 'Estado_Compra',
            },
        ),
        migrations.AddField(
            model_name='devolucionproveedor',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.empleados'),
        ),
        migrations.AddField(
            model_name='devolucionproveedor',
            name='id_factura_compra',
            field=models.ForeignKey(blank=True, db_column='id_factura_compra', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.facturacompra'),
        ),
        migrations.CreateModel(
            name='DevolucionCliente',
            fields=[
                ('id_devolucion_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_devolucion', models.TextField(blank=True, null=True)),
                ('cantidad_devuelta', models.IntegerField(blank=True, null=True)),
                ('precio_devolucion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.empleados')),
                ('id_medicamento', models.ForeignKey(blank=True, db_column='id_medicamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.medicamento')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.venta')),
            ],
            options={
                'db_table': 'Devolucion_Cliente',
            },
        ),
        migrations.CreateModel(
            name='CompraMedicamento',
            fields=[
                ('id_compra_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_factura_compra', models.ForeignKey(db_column='id_factura_compra', on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.facturacompra')),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.medicamento')),
            ],
            options={
                'db_table': 'Compra_Medicamento',
            },
        ),
    ]
