# Generated by Django 4.2.7 on 2025-11-27 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia_app', '0002_venta_cantidad_venta_id_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='id_medicamento',
            field=models.ForeignKey(blank=True, db_column='id_medicamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.medicamento'),
        ),
    ]
